<style>
  p {
    font-size: 30px;
  }

  p:hover {
    color: hsl(180, 100%, 60%);
  }

  h1 {
    font-size: 60px;
    color: hsl(210, 100%, 50%);
    background-color: hsl(0, 0%, 20%);
    padding: 10px;
  }

  h2 {
    font-size: 50px;
    color: hsl(270, 100%, 50%);
    background-color: hsl(0, 0%, 20%);
    padding: 10px;
  }

  h3 {
    font-size: 40px;
    color: hsl(60, 100%, 50%);
    background-color: hsl(0, 0%, 20%);
    padding: 10px;
  }
</style>


# Konsultacje
## RMT MiBM rok: 1, stopień: 1
### 17.04.2020

**Zad** Niech $A = (0, 0)$, $B = (2,0)$, $C = (2,1)$. Oblicz długość wysokości trójkąta $ABC$ opuszczonej z wierchołka $C$.

Wiemy, że $P_{ABC} = \frac{1}{2} \cdot |AB| \cdot h_C $.

$\overrightarrow{AB} = [2 - 0, 0 - 0] = [2, 0]$

$(((\forall_{a \in \mathbb{R}} \sqrt{a \cdot a} = |a|)))$

$|AB| = \|\overrightarrow{AB}\| = \sqrt{\overrightarrow{AB} \circ \overrightarrow{AB}} = \sqrt{ 2 \cdot 2 + 0 \cdot 0 } = 2$

$\overrightarrow{AC} = [2 - 0, 1 - 0] = [2, 1]$

$
P_{ABC} = \frac{1}{2}\cdot\mathrm{abs}( 
\begin{vmatrix}
    2 & 0\\
    2 & 1
\end{vmatrix}
$
$)=\frac{1}{2}\cdot |2 \cdot 1 - 1 \cdot 0 | = 1$

$h_C = 2 \cdot \frac{P_{ABC}}{|AB|} = 1$

**Odp** Szukana wysokość to $1$.

$V_{ABCD} = ?$

$P_{ACD} = ?$

**Zad** Niech $A = (2,1,3)$, $\mathbf{v} = [3,0,1]$, $\mathbf{w} = [-1,2,4]$. Obliczyć pole powierzchni równoległoboku rozpiętego przez wektory $\mathbf{v}$ i $\mathbf{w}$ w punkcie $A$.

$P_{Avw} = \| \mathbf{v} \times \mathbf{w} \|$

$((( \hat{i} = [1, 0, 0]$ $\hat{j} = [0, 1, 0]$ $\hat{k} = [0, 0, 1] )))$

$\mathbf{u} = \mathbf{v} \times \mathbf{w} =$
$
\begin{vmatrix}
    \hat{i} & \hat{j} & \hat{k}\\
    3 & 0 & 1\\
    -1 & 2 & 4
\end{vmatrix}
$
$=\hat{i} \begin{vmatrix} 0 & 1\\ 2 & 4\end{vmatrix} - \hat{j} \begin{vmatrix} 3 & 1\\ -1 & 4\end{vmatrix} + \hat{k} \begin{vmatrix} 3 & 0\\ -1 & 2\end{vmatrix}$
$= -2\hat{i} - 13\hat{j} + 6\hat{k} = [-2, -13, 6]$

$\|\mathbf{u}\| = \sqrt{\mathbf{u}\circ\mathbf{u}} = \sqrt{ (-2)\cdot(-2) + (-13)\cdot(-13) + 6\cdot 6 } = \sqrt{209}$

**Odp** Szukane pole powierzchni to $\sqrt{209}$.

In [7]:
import numpy

v = numpy.array([3,0,1])
print(v)
w = numpy.array([-1,2,4])
print(w)

u = numpy.cross(v,w)
print(u)

print(numpy.dot(u,u))
print(numpy.sqrt(numpy.dot(u,u)))
print(numpy.linalg.norm(u))

[3 0 1]
[-1  2  4]
[ -2 -13   6]
209
14.45683229480096
14.45683229480096


**Zad** Niech $B = (-100, 11, 99$), $\mathbf{u} = [1, 1, 1]$, $\mathbf{v} = [1, 0, 1]$, $\mathbf{w} = [-2, 0, 1]$. Obliczyć objętość równoległościanu rozpiętego przez wektory $\mathbf{u}, \mathbf{v}, \mathbf{w}$ w punkcie $B$.

$V_{B\mathbf{u}\mathbf{v}\mathbf{w}} = |\mathbf{u} \circ (\mathbf{v} \times \mathbf{w})| = |(\mathbf{u} \times \mathbf{v}) \circ \mathbf{w}|=abs($
$
\begin{vmatrix}
    1 & (1) & 1\\
    1 & (0) & 1\\
    -2 & (0) & 1
\end{vmatrix}
$
$)= abs( (-1)^{1+2} \cdot 1 \cdot \begin{vmatrix} 1 & 1\\ -2 & 1 \end{vmatrix} )$

$=|(-1)\cdot 1 \cdot 3| = |-3| = 3$

**Odp** Szukana objętość to 3.

In [6]:
u = numpy.array([1,1,1])
print(u)
v = numpy.array([1,0,1])
print(v)
w = numpy.array([-2,0,1])
print(w)

M = numpy.array([u,v,w])
print(M)

print()

print(numpy.dot(u,numpy.cross(v,w)))
print(numpy.dot(numpy.cross(u,v),w))
print(numpy.linalg.det(M))

[1 1 1]
[1 0 1]
[-2  0  1]
[[ 1  1  1]
 [ 1  0  1]
 [-2  0  1]]

-3
-3
-2.9999999999999996


$\| \perp \parallel \hat{i} [ \{ \cdot \circ \times \forall \exists$