<style>
  p {
    font-size: 30px;
  }

  p:hover {
    color: hsl(180, 100%, 60%);
  }

  h1 {
    font-size: 60px;
    color: hsl(210, 100%, 50%);
    background-color: hsl(0, 0%, 20%);
    padding: 10px;
  }

  h2 {
    font-size: 50px;
    color: hsl(270, 100%, 50%);
    background-color: hsl(0, 0%, 20%);
    padding: 10px;
  }

  h3 {
    font-size: 40px;
    color: hsl(60, 100%, 50%);
    background-color: hsl(0, 0%, 20%);
    padding: 10px;
  }
</style>


# Konsultacje
## RMT MiBM rok: 1, stopień: 1
### 10.04.2020

Znaleźć macierz odwrotną do macierzy $\begin{bmatrix}
    1 & 2 & 3\\
    2 & 3 & 7\\
    0 & 0 & 1
\end{bmatrix}$.

$
\begin{bmatrix}
    1 & 2 & 3 & | & 1 & 0 & 0\\
    2 & 3 & 7 & | & 0 & 1 & 0\\
    0 & 0 & 1 & | & 0 & 0 & 1
\end{bmatrix}
\overset{w_2 - 2 w_1}{\to}
\begin{bmatrix}
    1 & 2 & 3 & | & 1 & 0 & 0\\
    0 & -1 & 1 & | & -2 & 1 & 0\\
    0 & 0 & 1 & | & 0 & 0 & 1
\end{bmatrix}
\overset{w_2 * (-1)}{\to}
$

$
\begin{bmatrix}
    1 & 2 & 3 & | & 1 & 0 & 0\\
    0 & 1 & -1 & | & 2 & -1 & 0\\
    0 & 0 & 1 & | & 0 & 0 & 1
\end{bmatrix}
\overset{w_1 - 3 * w_3 \\ w_2 + w_3}{\to}
\begin{bmatrix}
    1 & 2 & 0 & | & 1 & 0 & -3\\
    0 & 1 & 0 & | & 2 & -1 & 1\\
    0 & 0 & 1 & | & 0 & 0 & 1
\end{bmatrix}
\overset{w_1 - 2 * w_2}{\to}
$

$
\begin{bmatrix}
    1 & 0 & 0 & | & -3 & 2 & -5\\
    0 & 1 & 0 & | & 2 & -1 & 1\\
    0 & 0 & 1 & | & 0 & 0 & 1
\end{bmatrix}
$

**Odp.:** Macierz odwrotna do danej macierzy to $\begin{bmatrix}
    -3 & 2 & -5\\
    2 & -1 & 1\\
    0 & 0 & 1
\end{bmatrix}$.

In [3]:
import numpy

A = numpy.array([[1,2,3],[2,3,7],[0,0,1]])
print(A)
print()
B = numpy.array([[-3,2,-5],[2,-1,1],[0,0,1]])
print(B)
print()

print(numpy.dot(A,B))
print()
print(numpy.dot(B,A))
print()

[[1 2 3]
 [2 3 7]
 [0 0 1]]

[[-3  2 -5]
 [ 2 -1  1]
 [ 0  0  1]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]



Znaleźć macierz odwrotną do macierzy $\begin{bmatrix}
    0 & 1 & 2 & 4\\
    2 & 3 & 5 & 9\\
    3 & 5 & 8 & 13\\
    3 & 5 & 7 & 11
\end{bmatrix}$.

$
\begin{bmatrix}
    0 & 1 & 2 & 4 & | & 1 & 0 & 0 & 0\\
    2 & 3 & 5 & 9 & | & 0 & 1 & 0 & 0\\
    3 & 5 & 8 & 13 & | & 0 & 0 & 1 & 0\\
    3 & 5 & 7 & 11 & | & 0 & 0 & 0 & 1
\end{bmatrix}
\overset{w_3 - w_2\\ w_4 - w_2}{\to}
\begin{bmatrix}
    0 & 1 & 2 & 4 & | & 1 & 0 & 0 & 0\\
    2 & 3 & 5 & 9 & | & 0 & 1 & 0 & 0\\
    1 & 2 & 3 & 4 & | & 0 & -1 & 1 & 0\\
    1 & 2 & 2 & 2 & | & 0 & -1 & 0 & 1
\end{bmatrix}
\overset{w_1 \leftrightarrow w_4}{\to}
$

$
\begin{bmatrix}
    1 & 2 & 2 & 2 & | & 0 & -1 & 0 & 1\\
    2 & 3 & 5 & 9 & | & 0 & 1 & 0 & 0\\
    1 & 2 & 3 & 4 & | & 0 & -1 & 1 & 0\\
    0 & 1 & 2 & 4 & | & 1 & 0 & 0 & 0
\end{bmatrix}
\overset{w_2 - 2 * w_1\\ w_3 - w_1}{\to}
\begin{bmatrix}
    1 & 2 & 2 & 2 & | & 0 & -1 & 0 & 1\\
    0 & -1 & 1 & 5 & | & 0 & 3 & 0 & -2\\
    0 & 0 & 1 & 2 & | & 0 & 0 & 1 & -1\\
    0 & 1 & 2 & 4 & | & 1 & 0 & 0 & 0
\end{bmatrix}
\overset{w_4 + w_2}{\to}
$

$
\begin{bmatrix}
    1 & 2 & 2 & 2 & | & 0 & -1 & 0 & 1\\
    0 & -1 & 1 & 5 & | & 0 & 3 & 0 & -2\\
    0 & 0 & 1 & 2 & | & 0 & 0 & 1 & -1\\
    0 & 0 & 3 & 9 & | & 1 & 3 & 0 & -2
\end{bmatrix}
\overset{w_4 - 3 * w_3}{\to}
\begin{bmatrix}
    1 & 2 & 2 & 2 & | & 0 & -1 & 0 & 1\\
    0 & -1 & 1 & 5 & | & 0 & 3 & 0 & -2\\
    0 & 0 & 1 & 2 & | & 0 & 0 & 1 & -1\\
    0 & 0 & 0 & 3 & | & 1 & 3 & -3 & 1
\end{bmatrix}
\overset{w2 * (-1)\\ w_4 * \frac{1}{3}}{\to}
$

$
\begin{bmatrix}
    1 & 2 & 2 & 2 & | & 0 & -1 & 0 & 1\\
    0 & 1 & -1 & -5 & | & 0 & -3 & 0 & 2\\
    0 & 0 & 1 & 2 & | & 0 & 0 & 1 & -1\\
    0 & 0 & 0 & 1 & | & \frac{1}{3} & 1 & -1 & \frac{1}{3}
\end{bmatrix}
\overset{w_2 + w_3}{\to}
\begin{bmatrix}
    1 & 2 & 2 & 2 & | & 0 & -1 & 0 & 1\\
    0 & 1 & 0 & -3 & | & 0 & -3 & 1 & 1\\
    0 & 0 & 1 & 2 & | & 0 & 0 & 1 & -1\\
    0 & 0 & 0 & 1 & | & \frac{1}{3} & 1 & -1 & \frac{1}{3}
\end{bmatrix}
\overset{w_1 - 2 * w_4\\ w_2 + 3*w_4\\ w_3 - 2 * w_4}{\to}
$

$
\begin{bmatrix}
    1 & 2 & 2 & 0 & | & \frac{-2}{3} & -3 & 2 & \frac{1}{3}\\
    0 & 1 & 0 & 0 & | & 1 & 0 & -2 & 2\\
    0 & 0 & 1 & 0 & | & \frac{-2}{3} & -2 & 3 & \frac{-5}{3}\\
    0 & 0 & 0 & 1 & | & \frac{1}{3} & 1 & -1 & \frac{1}{3}
\end{bmatrix}
\overset{w_1 - 2* w_2\\ w_1 - 2*w_3}{\to}
\begin{bmatrix}
    1 & 0 & 0 & 0 & | & \frac{-4}{3} & 1 & 0 & \frac{-1}{3}\\
    0 & 1 & 0 & 0 & | & 1 & 0 & -2 & 2\\
    0 & 0 & 1 & 0 & | & \frac{-2}{3} & -2 & 3 & \frac{-5}{3}\\
    0 & 0 & 0 & 1 & | & \frac{1}{3} & 1 & -1 & \frac{1}{3}
\end{bmatrix}
$

**Odp.:** Macierz odwrotna do danej macierzy to $\begin{bmatrix}
    \frac{-4}{3} & 1 & 0 & \frac{-1}{3}\\
    1 & 0 & -2 & 2\\
    \frac{-2}{3} & -2 & 3 & \frac{-5}{3}\\
    \frac{1}{3} & 1 & -1 & \frac{1}{3}
\end{bmatrix}$ 

In [7]:
A = numpy.array([[0,1,2,4],[2,3,5,9],[3,5,8,13],[3,5,7,11]])
print(A)
print()
B = numpy.array([[-4/3,1,0,-1/3],[1,0,-2,2],[-2/3,-2,3,-5/3],[1/3,1,-1,1/3]])
print(B)
print()

print(numpy.round(100*numpy.dot(A,B))/100)
print()
print(numpy.round(100*numpy.dot(B,A))/100)
print()

[[ 0  1  2  4]
 [ 2  3  5  9]
 [ 3  5  8 13]
 [ 3  5  7 11]]

[[-1.33333333  1.          0.         -0.33333333]
 [ 1.          0.         -2.          2.        ]
 [-0.66666667 -2.          3.         -1.66666667]
 [ 0.33333333  1.         -1.          0.33333333]]

[[ 1.  0.  0. -0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

