<style>
  p {
    font-size: 30px;
  }

  p:hover {
    color: hsl(180, 100%, 60%);
  }

  h1 {
    font-size: 60px;
    color: hsl(210, 100%, 50%);
    background-color: hsl(0, 0%, 20%);
    padding: 10px;
  }

  h2 {
    font-size: 50px;
    color: hsl(270, 100%, 50%);
    background-color: hsl(0, 0%, 20%);
    padding: 10px;
  }

  h3 {
    font-size: 40px;
    color: hsl(60, 100%, 50%);
    background-color: hsl(0, 0%, 20%);
    padding: 10px;
  }
</style>


# Konsultacje
## RMT ZiIP rok: 1, stopień: 1
### 25.05.2020

In [2]:
import numpy as np

print(np.linalg.inv([
    [5, 7, 9],
    [2, 3, 4],
    [4, 5, 9]
]))

[[ 2.33333333 -6.          0.33333333]
 [-0.66666667  3.         -0.66666667]
 [-0.66666667  1.          0.33333333]]
